INSTALL_DIR_ICON = /usr/share/pixmaps/
INSTALL_DIR_DESK = /usr/share/applications/

install:
	install -Dm 644 gtkevemon.svg ${INSTALL_DIR_ICON}/gtkevemon.svg
	install -Dm 644 gtkevemon.desktop ${INSTALL_DIR_DESK}/gtkevemon.desktop

uninstall:
	rm ${INSTALL_DIR_ICON}/gtkevemon.svg
	rm ${INSTALL_DIR_DESK}/gtkevemon.desktop
